[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "deltakit-decode"
version = "0.5.1"
description = "Deltakit (component deltakit-decode)"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = "Apache-2.0"
license-files = ["LICENSE"]

authors = [{ name = "Deltakit Team", email = "deltakit@riverlane.com" }]

classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Quantum Computing",
  "Typing :: Typed",
]
dependencies = [
  "deltakit-circuit~=0.5",
  "deltakit-core~=0.5",
  "numpy>=1.26",
  "networkx~=3.1",
  "seaborn~=0.12",
  "matplotlib~=3.5",
  "plotly~=6.5",
  "plotly-stubs",
  "pymatching~=2.2",
  "pymatching>=2.2.2,~=2.2; python_version >= '3.13'",
  "stim~=1.12",
  "pathos~=0.3",
  # This is the first version to be compatible with numpy>=2.0 according to
  # https://pandas.pydata.org/pandas-docs/stable/whatsnew/v2.2.2.html
  "pandas>=2.2.2",
  "pandas~=2.3; python_version >= '3.13'",
  "typing-extensions~=4.0",
  "tqdm~=4.66",
]

[dependency-groups]
test = [
  "pytest>=8.4",
  "pytest-cov>=7.0",
  "pytest-mock>=3.14",
  "pytest-skip-slow>=0.0.5",
  "pytest-lazy-fixtures>=1.0",
]
stubs = [
  "types-networkx~=3.1",
  "types-tqdm~=4.66",
  "pandas-stubs~=2.0",
  "types-seaborn~=0.12",
]
lint = [
  "mypy~=1.17",
  "ruff~=0.14",
  "typos~=1.34",
  "deptry~=0.23",
  { include-group = "stubs" },
]
security = ["bandit~=1.8", "ochrona~=2.0", "pip-audit~=2.7"]
dev = [
  { include-group = "test" },
  { include-group = "lint" },
  { include-group = "security" },
]

[project.urls]
Homepage = "https://github.com/Deltakit/deltakit"
"Bug Tracker" = "https://github.com/Deltakit/deltakit/issues"
Changelog = "https://github.com/Deltakit/deltakit/releases"

[tool.deptry]
known_first_party = ["deltakit_decode"]

[tool.deptry.per_rule_ignores]
DEP002 = ["plotly-stubs"]

[tool.mypy]
files = "src/**/*.py"
# The below list of disabled checks should eventually be empty.
disable_error_code = "arg-type,assignment,attr-defined,name-defined,index,misc"

[[tool.mypy.overrides]]
module = ["stim", "pathos", "pathos.pools", "pymatching"]
follow_untyped_imports = true

[tool.pytest.ini_options]
testpaths = ["./tests/"]
