import itertools
from collections.abc import Mapping, Sequence
from concurrent.futures import ProcessPoolExecutor

import numpy
import numpy.typing as npt
from deltakit_decode._mwpm_decoder import PyMatchingDecoder
from deltakit_decode.analysis._matching_decoder_managers import StimDecoderManager
from tqdm import tqdm

from deltakit_explorer.analysis.budget._interfaces import NoiseInterface
from deltakit_explorer.analysis.budget._memory import (
    MemoryGenerator,
    get_rotated_surface_code_memory_circuit,
)


def _generate_surface_code_memory_decoder_manager(
    distance: int,
    num_rounds: int,
    noise_model: NoiseInterface,
    memory_generator: MemoryGenerator,
) -> StimDecoderManager | None:
    """Generate a decoder manager with a rotated planar code memory experiment.

    Args:
        distance (int): distance of the rotated planar code memory experiment that
            should be generated by this function.
        num_rounds (int): number of stabilizer measurement rounds of the memory
            experiment generated by this function.
        noise_model (NoiseInterface): noise model that should be applied to the
            noiseless memory experiment generated within this function.

    Returns:
        a decoder manager that can then be run using ``RunAllAnalysisEngine`` or
        ``None`` if the problem is ill-formed.
    """
    circuit = memory_generator(distance, num_rounds)
    noisy_circuit = noise_model.apply(circuit)
    decoder, decoder_circuit = PyMatchingDecoder.construct_decoder_and_stim_circuit(
        noisy_circuit
    )
    metadata = {
        "distance": distance,
        "num_rounds": num_rounds,
        **{
            f"noise_{name}": p
            for name, p in zip(
                noise_model.parameter_names, noise_model.noise_parameters
            )
        },
    }

    return StimDecoderManager(decoder_circuit, decoder, metadata=metadata)


def _generate_surface_code_memory_decoder_manager_wrapper(
    data: tuple[int, int, NoiseInterface, MemoryGenerator],
) -> StimDecoderManager | None:
    return _generate_surface_code_memory_decoder_manager(*data)


def generate_decoder_managers_for_lambda(
    xi: npt.NDArray[numpy.floating],
    noise_model_type: type[NoiseInterface],
    num_rounds_by_distances: Mapping[int, Sequence[int]],
    max_workers: int = 1,
    memory_generator: MemoryGenerator = get_rotated_surface_code_memory_circuit,
) -> list[StimDecoderManager]:
    """Generate several decoder managers from the provided arguments for a rotated
    planar code memory experiment.

    This function should be used to generate in one call a description of all the
    sampling tasks that should be done in order to estimate the value of Λ on the
    provided noise parameters ``xi``.

    Note:
        Generating the tasks might be a long process, hence the presence of the
        ``max_worker`` parameter.

    Warning:
        This function will generate ``len(num_rounds) * len(distances) *
        numpy.prod(xi.shape[1:])`` sampling tasks. That quantity
        might grow quickly, so try to avoid providing too many entries in ``distances``
        and ``num_rounds`` except if you really need it.

    Args:
        xi (npt.NDArray[numpy.floating]): an array of shape ``(m, n)``, where ``m`` is
            the number of noise parameters needed by ``noise_model_type`` and ``n`` the
            number of points to evaluate Λ on.
        noise_model_type (Type[NoiseInterface]): noise model that should be applied to
            the noiseless memory experiments generated within this function.
        num_rounds_by_distances (Mapping[int, Sequence[int]]): the different number of
            rounds that will be used to estimate the logical error-rate per round for
            each code distance. As a rule of thumb, at least ``4`` entries should be
            provided and the maximum number of rounds should, if possible, give a
            logical error-rate above ``0.2`` for the largest distance and a logical
            error-rate below ``0.45`` for the smallest distance. You will not be able to
            check those thresholds everytime, but the standard errors computed will be
            lower if they are verified.
        max_workers (int): if provided, the number of parallel processes that are used
            to generate the sampling tasks. If not, default to ``1``.

    Returns:
        a list of decoder managers that can then be run using ``RunAllAnalysisEngine``.
    """
    # 0. Transposing to be able to iterate on different values.
    xi = xi.T
    # 1. Check input parameters
    for x in xi:
        if (message := noise_model_type.is_valid(x)) is not None:
            parameters = "[" + ", ".join(f"{float(v):.3g}" for v in x) + "]"
            msg = (
                f"The provided parameters {parameters} are invalid for noise model "
                f"{noise_model_type.__name__}. Reason is: '{message}'."
            )
            raise ValueError(msg)
    if max_workers <= 0:
        msg = f"Cannot have less than one worker. Asked for {max_workers} workers."
        raise ValueError(msg)
    # 2. Build an iterator on all the parameters we need to provide to the generation
    # method.
    total_circuits = (
        sum(len(nrounds) for nrounds in num_rounds_by_distances.values()) * xi.shape[0]
    )
    # (distance: int, num_rounds: int)
    distance_and_rounds_iterator = itertools.chain.from_iterable(
        zip(itertools.repeat(d, len(rounds)), rounds, strict=True)
        for d, rounds in num_rounds_by_distances.items()
    )
    # (distance: int, num_rounds: int, noise_model: noise_model_type, memory_generator)
    parameters_iterator = (
        (d, nr, nm, memgen)
        for ((d, nr), nm), memgen in zip(
            itertools.product(
                distance_and_rounds_iterator, (noise_model_type(x) for x in xi)
            ),
            itertools.repeat(memory_generator),
            strict=False,
        )
    )
    # 3. Generate the decoder managers
    decoder_managers: list[StimDecoderManager] = []
    if max_workers == 1:
        for distance, nrounds, noise_model, memgen in tqdm(
            parameters_iterator,
            total=total_circuits,
            desc="Generating quantum circuits",
        ):
            manager = _generate_surface_code_memory_decoder_manager(
                distance, nrounds, noise_model, memgen
            )
            assert manager is not None
            decoder_managers.append(manager)
        return decoder_managers
    # Else, we might use several workers
    with ProcessPoolExecutor(max_workers=max_workers) as pool:
        for manager in tqdm(
            iterable=pool.map(
                _generate_surface_code_memory_decoder_manager_wrapper,
                parameters_iterator,
            ),
            total=total_circuits,
            desc="Generating quantum circuits",
        ):
            assert manager is not None
            decoder_managers.append(manager)
        return decoder_managers
