---
name: Build, test, and publish stable wheels on PyPI
permissions:
  contents: read

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  pkg_name: deltakit

jobs:
  validation:
    name: Validate version bump
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Install release dependencies
        run: uv sync --python 3.14 --group release
      - name: Validate project version matches latest tag
        run: |
          git fetch --tags --quiet
          latest_tag=$(git tag -l \
            | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V \
            | tail -n1)
          version=$(echo "$latest_tag" | sed 's/^v//')
          uv run --no-sync python3 -m tools.check_version_match $version

  build-dists:
    name: Build distributions
    needs: [validation]
    runs-on: ubuntu-latest
    steps:
      - name: Check out deltakit repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Build deltakit wheel
        run: uv build --no-sources -o ./dist
      - name: Upload wheel artefacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.pkg_name }}
          path: ./dist/
          # No need to keep these as they will be published in this workflow.
          retention-days: 1

  test-wheels:
    name: Test imports after wheel install on ${{ matrix.os }}
    needs: [build-dists]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        dependency-resolution:
          - 'highest'
          - 'lowest-direct'
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
          ignore-empty-workdir: true
      - name: Recover deltakit distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.pkg_name }}
          path: ./dist/
          merge-multiple: true
      - name: Install and test on Unix
        if: matrix.os != 'windows-latest'
        run: |
          uv sync --python ${{ matrix.python-version }} --resolution ${{matrix.dependency-resolution}} --group test --find-links ./dist/
          uv pip install ./dist/deltakit*.whl
          uv run --python ${{ matrix.python-version }} --no-sync pytest .
          uv run python -c "import deltakit"
      - name: Install and test on Windows
        if: matrix.os == 'windows-latest'
        run: |
          uv sync --python ${{ matrix.python-version }} --resolution ${{matrix.dependency-resolution}} --group test --find-links ./dist/
          cd dist
          uv pip install deltakit*.whl
          cd ..
          uv run --python ${{ matrix.python-version }} --no-sync pytest .
          uv run python -c "import deltakit"


  test-sdists:
    name: Test imports after sdists install
    needs: [build-dists]
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
          ignore-empty-workdir: true
      - name: Recover deltakit distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.pkg_name }}
          path: ./dist/
          merge-multiple: true
      - name: Test install and imports
        run: |
          uv venv --python 3.10
          uv pip install --pre dist/*.tar.gz --find-links ./dist/
          uv run python -c "import deltakit"

  publish:
    name: Publish Python distribution to PyPI
    needs: [test-wheels, test-sdists]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.pkg_name }}
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Recover deltakit distribution files
        uses: actions/download-artifact@v8
        with:
          pattern: ${{ env.pkg_name }}
          path: ./dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
